name: Publish NPM Package

on: push

# this is what you want to do in real life
# on:
#     push:
#         paths: 
#             - sample-packages/npm/**

jobs:
    publish:
        name: "Publish to GitHub Packages"
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Setup node.js
              uses: actions/setup-node@v1
              with:
                node-version: 18
                registry-url: https://npm.pkg.github.com/ 
            - name: Publish to GitHub Packages
              run: npm publish
              env: 
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
