name: Publish NPM Package

on: push

# this is what you want to do in real life
# on:
#     push:
#         paths: 
#             - sample-packages/npm/**

jobs:
    publish:
        name: "Publish to GitHub Packages"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./sample-packages/npm
        steps: 
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
                registry-url: https://npm.pkg.github.com/ 
            
            # leave this out, we don't have any deps
            # - name: Install package deps
            #   run: npm ci
            
            - name: Publish to GitHub Packages
              run: npm publish
              env: 
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
